data:extend(
    {
        {
            type = "fluid",
            name = "milk",
            icon = "__baketorio__/graphics/milk.png",
            icon_size = 32,
            subgroup = "fluid",
            default_temperature = 25,
            heat_capacity = "0.1KJ",
            base_color = {r = 1, g = 1, b = 1},
            flow_color = {r = 1, g = 1, b = 1},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
        {
            type = "fluid",
            name = "cream",
            icon = "__baketorio__/graphics/cream.png",
            icon_size = 32,
            subgroup = "fluid",
            default_temperature = 25,
            heat_capacity = "0.1KJ",
            base_color = {r = 1, g = 0.76, b = 0.5},
            flow_color = {r = 1, g = 0.76, b = 0.5},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
        {
            type = "fluid",
            name = "liquid-butter",
            icon = "__baketorio__/graphics/butter_liquid.png",
            icon_size = 32,
            subgroup = "fluid",
            default_temperature = 25,
            heat_capacity = "0.1KJ",
            base_color = {r = 0.78, g = 0.69, b = 0.24},
            flow_color = {r = 0.78, g = 0.69, b = 0.24},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
        {
            type = "fluid",
            name = "unpasteurized-milk",
            icon = "__baketorio__/graphics/unpasteurized_milk.png",
            icon_size = 32,
            subgroup = "fluid",
            default_temperature = 25,
            heat_capacity = "0.1KJ",
            base_color = {r = 0.84, g = 1, b = 0.64},
            flow_color = {r = 0.84, g = 1, b = 0.64},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
    }
)